# Generated by Django 2.2.11 on 2020-03-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('musculoPrincipal', models.TextField()),
                ('musculoSecundario1', models.TextField()),
                ('musculoSecundario2', models.TextField(blank=True, null=True)),
                ('musculoSecundario3', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
