# Generated by Django 2.2.11 on 2020-03-09 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myGymLog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='ejerciciot',
            name='musculoPrincipal',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ejerciciot',
            name='musculoSecundario1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ejerciciot',
            name='musculoSecundario2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ejerciciot',
            name='musculoSecundario3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ejerciciot',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticiones', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=1, max_digits=4)),
                ('rir', models.IntegerField()),
                ('observaciones', models.TextField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myGymLog.Ejercicio')),
            ],
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='ejercicioT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myGymLog.EjercicioT'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='entrenamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myGymLog.Entrenamiento'),
        ),
    ]
