# Generated by Django 2.2.11 on 2020-03-10 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myGymLog', '0002_auto_20200309_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='ejercicio',
        ),
        migrations.AddField(
            model_name='serie',
            name='ejercicioT',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='myGymLog.EjercicioT'),
        ),
        migrations.AddField(
            model_name='serie',
            name='entrenamiento',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='myGymLog.Entrenamiento'),
        ),
        migrations.DeleteModel(
            name='Ejercicio',
        ),
    ]
